name: Deploy (local image only)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and run Docker container locally
    runs-on: [self-hosted, deploy_app]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image (local only)
        run: |
          echo "🔨 Construyendo imagen local..."
          docker build -t local_app:latest .

      - name: Run Docker container
        run: |
          echo "🛑 Eliminando contenedor anterior si existe..."
          docker rm -f app || true

          echo "🚀 Ejecutando contenedor desde imagen local"
          docker run -d --name app \
            -p 80:8080 \
            local_app:latest